

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class DropShip : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DropShip entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DropShip()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DropShip(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DropShip> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DropShip.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShip_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShip_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Dropshipid
        {
            get
            {
                return global::LightSwitchApplication.DropShip.DetailsClass.GetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Dropshipid);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dropshipid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dropshipid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dropshipid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.Guid> Guid
        {
            get
            {
                return global::LightSwitchApplication.DropShip.DetailsClass.GetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Guid);
            }
            set
            {
                global::LightSwitchApplication.DropShip.DetailsClass.SetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Guid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Guid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Guid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Guid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.DropShip.DetailsClass.GetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.DropShip.DetailsClass.SetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string login
        {
            get
            {
                return global::LightSwitchApplication.DropShip.DetailsClass.GetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.login);
            }
            set
            {
                global::LightSwitchApplication.DropShip.DetailsClass.SetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.login, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void login_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string password
        {
            get
            {
                return global::LightSwitchApplication.DropShip.DetailsClass.GetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.password);
            }
            set
            {
                global::LightSwitchApplication.DropShip.DetailsClass.SetValue(this, global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.password, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void password_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void password_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void password_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DropShip,
                global::LightSwitchApplication.DropShip.DetailsClass,
                global::LightSwitchApplication.DropShip.DetailsClass.IImplementation,
                global::LightSwitchApplication.DropShip.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Dropshipid;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>.Entry
                __DropShipEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>.Entry(
                    global::LightSwitchApplication.DropShip.DetailsClass.__DropShip_CreateNew,
                    global::LightSwitchApplication.DropShip.DetailsClass.__DropShip_Created,
                    global::LightSwitchApplication.DropShip.DetailsClass.__DropShip_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DropShip __DropShip_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DropShip> es)
            {
                return new global::LightSwitchApplication.DropShip(es);
            }
            private static void __DropShip_Created(global::LightSwitchApplication.DropShip e)
            {
                e.DropShip_Created();
            }
            private static bool __DropShip_AllowSaveWithErrors(global::LightSwitchApplication.DropShip e)
            {
                bool result = false;
                e.DropShip_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DropShip.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int> Dropshipid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Dropshipid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>> Guid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Guid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string> login
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.login) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string> password
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties.password) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Dropshipid { get; }
                new global::System.Nullable<global::System.Guid> Guid { get; set; }
                new string Name { get; set; }
                new string login { get; set; }
                new string password { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int>.Entry
                    Dropshipid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int>.Entry(
                        "Dropshipid",
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Dropshipid_Stub,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Dropshipid_ComputeIsReadOnly,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Dropshipid_Validate,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Dropshipid_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Dropshipid_OnValueChanged);
                private static void _Dropshipid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DropShip.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int>.Data> c, global::LightSwitchApplication.DropShip.DetailsClass d, object sf)
                {
                    c(d, ref d._Dropshipid, sf);
                }
                private static bool _Dropshipid_ComputeIsReadOnly(global::LightSwitchApplication.DropShip e)
                {
                    bool result = false;
                    e.Dropshipid_IsReadOnly(ref result);
                    return result;
                }
                private static void _Dropshipid_Validate(global::LightSwitchApplication.DropShip e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Dropshipid_Validate(r);
                }
                private static int _Dropshipid_GetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d)
                {
                    return d.ImplementationEntity.Dropshipid;
                }
                private static void _Dropshipid_OnValueChanged(global::LightSwitchApplication.DropShip e)
                {
                    e.Dropshipid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>>.Entry
                    Guid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>>.Entry(
                        "Guid",
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_Stub,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_ComputeIsReadOnly,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_Validate,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_GetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_SetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Guid_OnValueChanged);
                private static void _Guid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DropShip.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>>.Data> c, global::LightSwitchApplication.DropShip.DetailsClass d, object sf)
                {
                    c(d, ref d._Guid, sf);
                }
                private static bool _Guid_ComputeIsReadOnly(global::LightSwitchApplication.DropShip e)
                {
                    bool result = false;
                    e.Guid_IsReadOnly(ref result);
                    return result;
                }
                private static void _Guid_Validate(global::LightSwitchApplication.DropShip e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Guid_Validate(r);
                }
                private static global::System.Nullable<global::System.Guid> _Guid_GetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d)
                {
                    return d.ImplementationEntity.Guid;
                }
                private static void _Guid_SetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d, global::System.Nullable<global::System.Guid> v)
                {
                    d.ImplementationEntity.Guid = v;
                }
                private static void _Guid_OnValueChanged(global::LightSwitchApplication.DropShip e)
                {
                    e.Guid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DropShip.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data> c, global::LightSwitchApplication.DropShip.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.DropShip e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.DropShip e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.DropShip e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry
                    login = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry(
                        "login",
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_Stub,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_ComputeIsReadOnly,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_Validate,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_GetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_SetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._login_OnValueChanged);
                private static void _login_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DropShip.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data> c, global::LightSwitchApplication.DropShip.DetailsClass d, object sf)
                {
                    c(d, ref d._login, sf);
                }
                private static bool _login_ComputeIsReadOnly(global::LightSwitchApplication.DropShip e)
                {
                    bool result = false;
                    e.login_IsReadOnly(ref result);
                    return result;
                }
                private static void _login_Validate(global::LightSwitchApplication.DropShip e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.login_Validate(r);
                }
                private static string _login_GetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d)
                {
                    return d.ImplementationEntity.login;
                }
                private static void _login_SetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d, string v)
                {
                    d.ImplementationEntity.login = v;
                }
                private static void _login_OnValueChanged(global::LightSwitchApplication.DropShip e)
                {
                    e.login_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry
                    password = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Entry(
                        "password",
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_Stub,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_ComputeIsReadOnly,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_Validate,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_GetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_SetImplementationValue,
                        global::LightSwitchApplication.DropShip.DetailsClass.PropertySetProperties._password_OnValueChanged);
                private static void _password_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DropShip.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data> c, global::LightSwitchApplication.DropShip.DetailsClass d, object sf)
                {
                    c(d, ref d._password, sf);
                }
                private static bool _password_ComputeIsReadOnly(global::LightSwitchApplication.DropShip e)
                {
                    bool result = false;
                    e.password_IsReadOnly(ref result);
                    return result;
                }
                private static void _password_Validate(global::LightSwitchApplication.DropShip e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.password_Validate(r);
                }
                private static string _password_GetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d)
                {
                    return d.ImplementationEntity.password;
                }
                private static void _password_SetImplementationValue(global::LightSwitchApplication.DropShip.DetailsClass d, string v)
                {
                    d.ImplementationEntity.password = v;
                }
                private static void _password_OnValueChanged(global::LightSwitchApplication.DropShip e)
                {
                    e.password_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, int>.Data _Dropshipid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, global::System.Nullable<global::System.Guid>>.Data _Guid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data _login;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DropShip, global::LightSwitchApplication.DropShip.DetailsClass, string>.Data _password;
            
        }
    
        #endregion
    }
    
    #endregion
}
