

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class aspnet_WebEvent_Event : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the aspnet_WebEvent_Event entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public aspnet_WebEvent_Event()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public aspnet_WebEvent_Event(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.aspnet_WebEvent_Event> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void aspnet_WebEvent_Event_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void aspnet_WebEvent_Event_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EventId
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventId);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EventTimeUtc
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTimeUtc);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTimeUtc, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTimeUtc_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTimeUtc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTimeUtc_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EventTime
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTime);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EventType
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventType);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal EventSequence
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventSequence);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventSequence, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSequence_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSequence_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSequence_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal EventOccurrence
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventOccurrence);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventOccurrence, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventOccurrence_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventOccurrence_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventOccurrence_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EventCode
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventCode);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EventDetailCode
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventDetailCode);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventDetailCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventDetailCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventDetailCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventDetailCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Message
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Message);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Message, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ApplicationPath
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationPath);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationPath, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationPath_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationPath_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationPath_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ApplicationVirtualPath
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationVirtualPath);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationVirtualPath, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationVirtualPath_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationVirtualPath_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationVirtualPath_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MachineName
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.MachineName);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.MachineName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MachineName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MachineName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MachineName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RequestUrl
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.RequestUrl);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.RequestUrl, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RequestUrl_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RequestUrl_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RequestUrl_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ExceptionType
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ExceptionType);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ExceptionType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExceptionType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Details1
        {
            get
            {
                return global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.GetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Details1);
            }
            set
            {
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.SetValue(this, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Details1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Details1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Details1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Details1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.aspnet_WebEvent_Event,
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass,
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.IImplementation,
                global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>.Entry
                __aspnet_WebEvent_EventEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>.Entry(
                    global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.__aspnet_WebEvent_Event_CreateNew,
                    global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.__aspnet_WebEvent_Event_Created,
                    global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.__aspnet_WebEvent_Event_AllowSaveWithErrors);
            private static global::LightSwitchApplication.aspnet_WebEvent_Event __aspnet_WebEvent_Event_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.aspnet_WebEvent_Event> es)
            {
                return new global::LightSwitchApplication.aspnet_WebEvent_Event(es);
            }
            private static void __aspnet_WebEvent_Event_Created(global::LightSwitchApplication.aspnet_WebEvent_Event e)
            {
                e.aspnet_WebEvent_Event_Created();
            }
            private static bool __aspnet_WebEvent_Event_AllowSaveWithErrors(global::LightSwitchApplication.aspnet_WebEvent_Event e)
            {
                bool result = false;
                e.aspnet_WebEvent_Event_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> EventId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime> EventTimeUtc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTimeUtc) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime> EventTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> EventType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal> EventSequence
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventSequence) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal> EventOccurrence
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventOccurrence) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int> EventCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int> EventDetailCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.EventDetailCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> Message
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Message) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> ApplicationPath
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationPath) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> ApplicationVirtualPath
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ApplicationVirtualPath) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> MachineName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.MachineName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> RequestUrl
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.RequestUrl) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> ExceptionType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.ExceptionType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string> Details1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties.Details1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string EventId { get; set; }
                new global::System.DateTime EventTimeUtc { get; set; }
                new global::System.DateTime EventTime { get; set; }
                new string EventType { get; set; }
                new decimal EventSequence { get; set; }
                new decimal EventOccurrence { get; set; }
                new int EventCode { get; set; }
                new int EventDetailCode { get; set; }
                new string Message { get; set; }
                new string ApplicationPath { get; set; }
                new string ApplicationVirtualPath { get; set; }
                new string MachineName { get; set; }
                new string RequestUrl { get; set; }
                new string ExceptionType { get; set; }
                new string Details1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    EventId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "EventId",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventId_OnValueChanged);
                private static void _EventId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventId, sf);
                }
                private static bool _EventId_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventId_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventId_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventId_Validate(r);
                }
                private static string _EventId_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventId;
                }
                private static void _EventId_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EventId = v;
                }
                private static void _EventId_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Entry
                    EventTimeUtc = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Entry(
                        "EventTimeUtc",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTimeUtc_OnValueChanged);
                private static void _EventTimeUtc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventTimeUtc, sf);
                }
                private static bool _EventTimeUtc_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventTimeUtc_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventTimeUtc_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventTimeUtc_Validate(r);
                }
                private static global::System.DateTime _EventTimeUtc_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventTimeUtc;
                }
                private static void _EventTimeUtc_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.EventTimeUtc = global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _EventTimeUtc_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventTimeUtc_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Entry
                    EventTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Entry(
                        "EventTime",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventTime_OnValueChanged);
                private static void _EventTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventTime, sf);
                }
                private static bool _EventTime_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventTime_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventTime_Validate(r);
                }
                private static global::System.DateTime _EventTime_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventTime;
                }
                private static void _EventTime_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.EventTime = global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _EventTime_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    EventType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "EventType",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventType_OnValueChanged);
                private static void _EventType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventType, sf);
                }
                private static bool _EventType_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventType_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventType_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventType_Validate(r);
                }
                private static string _EventType_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventType;
                }
                private static void _EventType_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EventType = v;
                }
                private static void _EventType_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Entry
                    EventSequence = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Entry(
                        "EventSequence",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventSequence_OnValueChanged);
                private static void _EventSequence_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventSequence, sf);
                }
                private static bool _EventSequence_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventSequence_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventSequence_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventSequence_Validate(r);
                }
                private static decimal _EventSequence_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventSequence;
                }
                private static void _EventSequence_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.EventSequence = v;
                }
                private static void _EventSequence_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventSequence_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Entry
                    EventOccurrence = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Entry(
                        "EventOccurrence",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventOccurrence_OnValueChanged);
                private static void _EventOccurrence_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventOccurrence, sf);
                }
                private static bool _EventOccurrence_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventOccurrence_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventOccurrence_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventOccurrence_Validate(r);
                }
                private static decimal _EventOccurrence_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventOccurrence;
                }
                private static void _EventOccurrence_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.EventOccurrence = v;
                }
                private static void _EventOccurrence_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventOccurrence_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Entry
                    EventCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Entry(
                        "EventCode",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventCode_OnValueChanged);
                private static void _EventCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventCode, sf);
                }
                private static bool _EventCode_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventCode_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventCode_Validate(r);
                }
                private static int _EventCode_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventCode;
                }
                private static void _EventCode_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EventCode = v;
                }
                private static void _EventCode_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Entry
                    EventDetailCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Entry(
                        "EventDetailCode",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._EventDetailCode_OnValueChanged);
                private static void _EventDetailCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._EventDetailCode, sf);
                }
                private static bool _EventDetailCode_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.EventDetailCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _EventDetailCode_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EventDetailCode_Validate(r);
                }
                private static int _EventDetailCode_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.EventDetailCode;
                }
                private static void _EventDetailCode_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EventDetailCode = v;
                }
                private static void _EventDetailCode_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.EventDetailCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    Message = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "Message",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Message_OnValueChanged);
                private static void _Message_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._Message, sf);
                }
                private static bool _Message_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.Message_IsReadOnly(ref result);
                    return result;
                }
                private static void _Message_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Message_Validate(r);
                }
                private static string _Message_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.Message;
                }
                private static void _Message_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Message = v;
                }
                private static void _Message_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.Message_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    ApplicationPath = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "ApplicationPath",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationPath_OnValueChanged);
                private static void _ApplicationPath_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationPath, sf);
                }
                private static bool _ApplicationPath_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.ApplicationPath_IsReadOnly(ref result);
                    return result;
                }
                private static void _ApplicationPath_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ApplicationPath_Validate(r);
                }
                private static string _ApplicationPath_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.ApplicationPath;
                }
                private static void _ApplicationPath_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ApplicationPath = v;
                }
                private static void _ApplicationPath_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.ApplicationPath_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    ApplicationVirtualPath = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "ApplicationVirtualPath",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ApplicationVirtualPath_OnValueChanged);
                private static void _ApplicationVirtualPath_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationVirtualPath, sf);
                }
                private static bool _ApplicationVirtualPath_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.ApplicationVirtualPath_IsReadOnly(ref result);
                    return result;
                }
                private static void _ApplicationVirtualPath_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ApplicationVirtualPath_Validate(r);
                }
                private static string _ApplicationVirtualPath_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.ApplicationVirtualPath;
                }
                private static void _ApplicationVirtualPath_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ApplicationVirtualPath = v;
                }
                private static void _ApplicationVirtualPath_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.ApplicationVirtualPath_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    MachineName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "MachineName",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._MachineName_OnValueChanged);
                private static void _MachineName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._MachineName, sf);
                }
                private static bool _MachineName_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.MachineName_IsReadOnly(ref result);
                    return result;
                }
                private static void _MachineName_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MachineName_Validate(r);
                }
                private static string _MachineName_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.MachineName;
                }
                private static void _MachineName_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MachineName = v;
                }
                private static void _MachineName_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.MachineName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    RequestUrl = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "RequestUrl",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._RequestUrl_OnValueChanged);
                private static void _RequestUrl_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._RequestUrl, sf);
                }
                private static bool _RequestUrl_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.RequestUrl_IsReadOnly(ref result);
                    return result;
                }
                private static void _RequestUrl_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RequestUrl_Validate(r);
                }
                private static string _RequestUrl_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.RequestUrl;
                }
                private static void _RequestUrl_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RequestUrl = v;
                }
                private static void _RequestUrl_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.RequestUrl_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    ExceptionType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "ExceptionType",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._ExceptionType_OnValueChanged);
                private static void _ExceptionType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._ExceptionType, sf);
                }
                private static bool _ExceptionType_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.ExceptionType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExceptionType_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExceptionType_Validate(r);
                }
                private static string _ExceptionType_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.ExceptionType;
                }
                private static void _ExceptionType_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ExceptionType = v;
                }
                private static void _ExceptionType_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.ExceptionType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry
                    Details1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Entry(
                        "Details1",
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_Stub,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_ComputeIsReadOnly,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_Validate,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_GetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_SetImplementationValue,
                        global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass.PropertySetProperties._Details1_OnValueChanged);
                private static void _Details1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data> c, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, object sf)
                {
                    c(d, ref d._Details1, sf);
                }
                private static bool _Details1_ComputeIsReadOnly(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    bool result = false;
                    e.Details1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Details1_Validate(global::LightSwitchApplication.aspnet_WebEvent_Event e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Details1_Validate(r);
                }
                private static string _Details1_GetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d)
                {
                    return d.ImplementationEntity.Details1;
                }
                private static void _Details1_SetImplementationValue(global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Details1 = v;
                }
                private static void _Details1_OnValueChanged(global::LightSwitchApplication.aspnet_WebEvent_Event e)
                {
                    e.Details1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _EventId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Data _EventTimeUtc;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, global::System.DateTime>.Data _EventTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _EventType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Data _EventSequence;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, decimal>.Data _EventOccurrence;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Data _EventCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, int>.Data _EventDetailCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _Message;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _ApplicationPath;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _ApplicationVirtualPath;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _MachineName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _RequestUrl;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _ExceptionType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.aspnet_WebEvent_Event, global::LightSwitchApplication.aspnet_WebEvent_Event.DetailsClass, string>.Data _Details1;
            
        }
    
        #endregion
    }
    
    #endregion
}
