

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Batch : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Batch entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Batch()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Batch(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Batch> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Batch.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Batch_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Batch_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Batchid
        {
            get
            {
                return global::LightSwitchApplication.Batch.DetailsClass.GetValue(this, global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.Batchid);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Batchid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Batchid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Batchid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateStamp
        {
            get
            {
                return global::LightSwitchApplication.Batch.DetailsClass.GetValue(this, global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DateStamp);
            }
            set
            {
                global::LightSwitchApplication.Batch.DetailsClass.SetValue(this, global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DateStamp, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStamp_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStamp_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStamp_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> DropShipID
        {
            get
            {
                return global::LightSwitchApplication.Batch.DetailsClass.GetValue(this, global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DropShipID);
            }
            set
            {
                global::LightSwitchApplication.Batch.DetailsClass.SetValue(this, global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DropShipID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Batch,
                global::LightSwitchApplication.Batch.DetailsClass,
                global::LightSwitchApplication.Batch.DetailsClass.IImplementation,
                global::LightSwitchApplication.Batch.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.Batchid;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>.Entry
                __BatchEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>.Entry(
                    global::LightSwitchApplication.Batch.DetailsClass.__Batch_CreateNew,
                    global::LightSwitchApplication.Batch.DetailsClass.__Batch_Created,
                    global::LightSwitchApplication.Batch.DetailsClass.__Batch_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Batch __Batch_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Batch> es)
            {
                return new global::LightSwitchApplication.Batch(es);
            }
            private static void __Batch_Created(global::LightSwitchApplication.Batch e)
            {
                e.Batch_Created();
            }
            private static bool __Batch_AllowSaveWithErrors(global::LightSwitchApplication.Batch e)
            {
                bool result = false;
                e.Batch_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Batch.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int> Batchid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.Batchid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>> DateStamp
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DateStamp) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>> DropShipID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties.DropShipID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Batchid { get; }
                new global::System.Nullable<global::System.DateTime> DateStamp { get; set; }
                new global::System.Nullable<int> DropShipID { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int>.Entry
                    Batchid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int>.Entry(
                        "Batchid",
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._Batchid_Stub,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._Batchid_ComputeIsReadOnly,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._Batchid_Validate,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._Batchid_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._Batchid_OnValueChanged);
                private static void _Batchid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Batch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int>.Data> c, global::LightSwitchApplication.Batch.DetailsClass d, object sf)
                {
                    c(d, ref d._Batchid, sf);
                }
                private static bool _Batchid_ComputeIsReadOnly(global::LightSwitchApplication.Batch e)
                {
                    bool result = false;
                    e.Batchid_IsReadOnly(ref result);
                    return result;
                }
                private static void _Batchid_Validate(global::LightSwitchApplication.Batch e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Batchid_Validate(r);
                }
                private static int _Batchid_GetImplementationValue(global::LightSwitchApplication.Batch.DetailsClass d)
                {
                    return d.ImplementationEntity.Batchid;
                }
                private static void _Batchid_OnValueChanged(global::LightSwitchApplication.Batch e)
                {
                    e.Batchid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateStamp = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateStamp",
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_Stub,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_ComputeIsReadOnly,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_Validate,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_GetImplementationValue,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_SetImplementationValue,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DateStamp_OnValueChanged);
                private static void _DateStamp_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Batch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Batch.DetailsClass d, object sf)
                {
                    c(d, ref d._DateStamp, sf);
                }
                private static bool _DateStamp_ComputeIsReadOnly(global::LightSwitchApplication.Batch e)
                {
                    bool result = false;
                    e.DateStamp_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateStamp_Validate(global::LightSwitchApplication.Batch e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateStamp_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateStamp_GetImplementationValue(global::LightSwitchApplication.Batch.DetailsClass d)
                {
                    return d.ImplementationEntity.DateStamp;
                }
                private static void _DateStamp_SetImplementationValue(global::LightSwitchApplication.Batch.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateStamp = global::LightSwitchApplication.Batch.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateStamp_OnValueChanged(global::LightSwitchApplication.Batch e)
                {
                    e.DateStamp_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>>.Entry
                    DropShipID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>>.Entry(
                        "DropShipID",
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_Stub,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_Validate,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_GetImplementationValue,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_SetImplementationValue,
                        global::LightSwitchApplication.Batch.DetailsClass.PropertySetProperties._DropShipID_OnValueChanged);
                private static void _DropShipID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Batch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Batch.DetailsClass d, object sf)
                {
                    c(d, ref d._DropShipID, sf);
                }
                private static bool _DropShipID_ComputeIsReadOnly(global::LightSwitchApplication.Batch e)
                {
                    bool result = false;
                    e.DropShipID_IsReadOnly(ref result);
                    return result;
                }
                private static void _DropShipID_Validate(global::LightSwitchApplication.Batch e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DropShipID_Validate(r);
                }
                private static global::System.Nullable<int> _DropShipID_GetImplementationValue(global::LightSwitchApplication.Batch.DetailsClass d)
                {
                    return d.ImplementationEntity.DropShipID;
                }
                private static void _DropShipID_SetImplementationValue(global::LightSwitchApplication.Batch.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.DropShipID = v;
                }
                private static void _DropShipID_OnValueChanged(global::LightSwitchApplication.Batch e)
                {
                    e.DropShipID_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, int>.Data _Batchid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateStamp;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Batch, global::LightSwitchApplication.Batch.DetailsClass, global::System.Nullable<int>>.Data _DropShipID;
            
        }
    
        #endregion
    }
    
    #endregion
}
