

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Gift : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Gift entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Gift()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Gift(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Gift> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Gift.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Gift_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Gift_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SKU
        {
            get
            {
                return global::LightSwitchApplication.Gift.DetailsClass.GetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.SKU);
            }
            set
            {
                global::LightSwitchApplication.Gift.DetailsClass.SetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.SKU, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SKU_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SKU_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SKU_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Gift.DetailsClass.GetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Gift.DetailsClass.SetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ORG
        {
            get
            {
                return global::LightSwitchApplication.Gift.DetailsClass.GetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.ORG);
            }
            set
            {
                global::LightSwitchApplication.Gift.DetailsClass.SetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.ORG, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ORG_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ORG_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ORG_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Gift1
        {
            get
            {
                return global::LightSwitchApplication.Gift.DetailsClass.GetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Gift1);
            }
            set
            {
                global::LightSwitchApplication.Gift.DetailsClass.SetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Gift1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Gift1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Gift1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Gift1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> DropShipID
        {
            get
            {
                return global::LightSwitchApplication.Gift.DetailsClass.GetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.DropShipID);
            }
            set
            {
                global::LightSwitchApplication.Gift.DetailsClass.SetValue(this, global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.DropShipID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DropShipID_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Gift,
                global::LightSwitchApplication.Gift.DetailsClass,
                global::LightSwitchApplication.Gift.DetailsClass.IImplementation,
                global::LightSwitchApplication.Gift.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.SKU;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>.Entry
                __GiftEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>.Entry(
                    global::LightSwitchApplication.Gift.DetailsClass.__Gift_CreateNew,
                    global::LightSwitchApplication.Gift.DetailsClass.__Gift_Created,
                    global::LightSwitchApplication.Gift.DetailsClass.__Gift_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Gift __Gift_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Gift> es)
            {
                return new global::LightSwitchApplication.Gift(es);
            }
            private static void __Gift_Created(global::LightSwitchApplication.Gift e)
            {
                e.Gift_Created();
            }
            private static bool __Gift_AllowSaveWithErrors(global::LightSwitchApplication.Gift e)
            {
                bool result = false;
                e.Gift_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Gift.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string> SKU
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.SKU) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string> ORG
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.ORG) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>> Gift1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.Gift1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>> DropShipID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties.DropShipID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string SKU { get; set; }
                new string Description { get; set; }
                new string ORG { get; set; }
                new global::System.Nullable<decimal> Gift1 { get; set; }
                new global::System.Nullable<int> DropShipID { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry
                    SKU = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry(
                        "SKU",
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_Stub,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_ComputeIsReadOnly,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_Validate,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_GetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_SetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._SKU_OnValueChanged);
                private static void _SKU_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Gift.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data> c, global::LightSwitchApplication.Gift.DetailsClass d, object sf)
                {
                    c(d, ref d._SKU, sf);
                }
                private static bool _SKU_ComputeIsReadOnly(global::LightSwitchApplication.Gift e)
                {
                    bool result = false;
                    e.SKU_IsReadOnly(ref result);
                    return result;
                }
                private static void _SKU_Validate(global::LightSwitchApplication.Gift e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SKU_Validate(r);
                }
                private static string _SKU_GetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d)
                {
                    return d.ImplementationEntity.SKU;
                }
                private static void _SKU_SetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SKU = v;
                }
                private static void _SKU_OnValueChanged(global::LightSwitchApplication.Gift e)
                {
                    e.SKU_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Gift.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data> c, global::LightSwitchApplication.Gift.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Gift e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Gift e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Gift e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry
                    ORG = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Entry(
                        "ORG",
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_Stub,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_ComputeIsReadOnly,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_Validate,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_GetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_SetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._ORG_OnValueChanged);
                private static void _ORG_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Gift.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data> c, global::LightSwitchApplication.Gift.DetailsClass d, object sf)
                {
                    c(d, ref d._ORG, sf);
                }
                private static bool _ORG_ComputeIsReadOnly(global::LightSwitchApplication.Gift e)
                {
                    bool result = false;
                    e.ORG_IsReadOnly(ref result);
                    return result;
                }
                private static void _ORG_Validate(global::LightSwitchApplication.Gift e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ORG_Validate(r);
                }
                private static string _ORG_GetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d)
                {
                    return d.ImplementationEntity.ORG;
                }
                private static void _ORG_SetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ORG = v;
                }
                private static void _ORG_OnValueChanged(global::LightSwitchApplication.Gift e)
                {
                    e.ORG_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Gift1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Gift1",
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_Stub,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_Validate,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_GetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_SetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._Gift1_OnValueChanged);
                private static void _Gift1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Gift.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.Gift.DetailsClass d, object sf)
                {
                    c(d, ref d._Gift1, sf);
                }
                private static bool _Gift1_ComputeIsReadOnly(global::LightSwitchApplication.Gift e)
                {
                    bool result = false;
                    e.Gift1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Gift1_Validate(global::LightSwitchApplication.Gift e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Gift1_Validate(r);
                }
                private static global::System.Nullable<decimal> _Gift1_GetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d)
                {
                    return d.ImplementationEntity.Gift1;
                }
                private static void _Gift1_SetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Gift1 = v;
                }
                private static void _Gift1_OnValueChanged(global::LightSwitchApplication.Gift e)
                {
                    e.Gift1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>>.Entry
                    DropShipID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>>.Entry(
                        "DropShipID",
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_Stub,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_Validate,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_GetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_SetImplementationValue,
                        global::LightSwitchApplication.Gift.DetailsClass.PropertySetProperties._DropShipID_OnValueChanged);
                private static void _DropShipID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Gift.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Gift.DetailsClass d, object sf)
                {
                    c(d, ref d._DropShipID, sf);
                }
                private static bool _DropShipID_ComputeIsReadOnly(global::LightSwitchApplication.Gift e)
                {
                    bool result = false;
                    e.DropShipID_IsReadOnly(ref result);
                    return result;
                }
                private static void _DropShipID_Validate(global::LightSwitchApplication.Gift e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DropShipID_Validate(r);
                }
                private static global::System.Nullable<int> _DropShipID_GetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d)
                {
                    return d.ImplementationEntity.DropShipID;
                }
                private static void _DropShipID_SetImplementationValue(global::LightSwitchApplication.Gift.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.DropShipID = v;
                }
                private static void _DropShipID_OnValueChanged(global::LightSwitchApplication.Gift e)
                {
                    e.DropShipID_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data _SKU;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, string>.Data _ORG;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<decimal>>.Data _Gift1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Gift, global::LightSwitchApplication.Gift.DetailsClass, global::System.Nullable<int>>.Data _DropShipID;
            
        }
    
        #endregion
    }
    
    #endregion
}
