<?xml version="1.0" encoding="utf-8"?><Database Name="pooptesst" Class="PoopDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=jserver;Initial Catalog=pooptesst;Persist Security Info=True;User ID=poop" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pooptesstConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Gift" Member="Gifts">
    <Type Name="Gift">
      <Column Name="SKU" Type="System.String" DbType="NChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="ORG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Gift" Member="Gift1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DropShipID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cust_to_org" Member="Cust_to_orgs">
    <Type Name="Cust_to_org">
      <Column Name="OrgID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="LineNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Warehouse" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipStatus" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GiftPaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OrgId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xml" Member="xmls">
    <Type Name="xml">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="xml" Member="xml1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.OrderHeader" Member="OrderHeaders">
    <Type Name="OrderHeader">
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BillingAddr1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BillingAddr2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="City" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ZipCode" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CompanyName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BillingFirstName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BillingLastName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CustomerIPAddr" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CustomerID" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Gift" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrderComments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrderDate" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrderStatus" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipToAddr1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipToAddr2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipCompanyName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipCity" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipZipCode" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShipPhone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="OrderDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetOrgID" Method="GetOrgID">
    <Parameter Name="ORGID" Parameter="oRGID" Type="System.String" DbType="NChar(100)" />
    <ElementType Name="GetOrgIDResult">
      <Column Name="ORGID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>