#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pooptesst")]
	public partial class PoopDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGift(Gift instance);
    partial void UpdateGift(Gift instance);
    partial void DeleteGift(Gift instance);
    partial void InsertCust_to_org(Cust_to_org instance);
    partial void UpdateCust_to_org(Cust_to_org instance);
    partial void DeleteCust_to_org(Cust_to_org instance);
    partial void InsertOrderDetail(OrderDetail instance);
    partial void UpdateOrderDetail(OrderDetail instance);
    partial void DeleteOrderDetail(OrderDetail instance);
    partial void Insertxml(xml instance);
    partial void Updatexml(xml instance);
    partial void Deletexml(xml instance);
    partial void InsertOrderHeader(OrderHeader instance);
    partial void UpdateOrderHeader(OrderHeader instance);
    partial void DeleteOrderHeader(OrderHeader instance);
    #endregion
		
		public PoopDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pooptesstConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PoopDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gift> Gifts
		{
			get
			{
				return this.GetTable<Gift>();
			}
		}
		
		public System.Data.Linq.Table<Cust_to_org> Cust_to_orgs
		{
			get
			{
				return this.GetTable<Cust_to_org>();
			}
		}
		
		public System.Data.Linq.Table<OrderDetail> OrderDetails
		{
			get
			{
				return this.GetTable<OrderDetail>();
			}
		}
		
		public System.Data.Linq.Table<xml> xmls
		{
			get
			{
				return this.GetTable<xml>();
			}
		}
		
		public System.Data.Linq.Table<OrderHeader> OrderHeaders
		{
			get
			{
				return this.GetTable<OrderHeader>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOrgID")]
		public ISingleResult<GetOrgIDResult> GetOrgID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORGID", DbType="NChar(100)")] string oRGID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oRGID);
			return ((ISingleResult<GetOrgIDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gift")]
	public partial class Gift : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SKU;
		
		private string _Description;
		
		private string _ORG;
		
		private System.Nullable<decimal> _Gift1;
		
		private System.Nullable<int> _DropShipID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnORGChanging(string value);
    partial void OnORGChanged();
    partial void OnGift1Changing(System.Nullable<decimal> value);
    partial void OnGift1Changed();
    partial void OnDropShipIDChanging(System.Nullable<int> value);
    partial void OnDropShipIDChanged();
    #endregion
		
		public Gift()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG", DbType="NChar(10)")]
		public string ORG
		{
			get
			{
				return this._ORG;
			}
			set
			{
				if ((this._ORG != value))
				{
					this.OnORGChanging(value);
					this.SendPropertyChanging();
					this._ORG = value;
					this.SendPropertyChanged("ORG");
					this.OnORGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Gift", Storage="_Gift1", DbType="Money")]
		public System.Nullable<decimal> Gift1
		{
			get
			{
				return this._Gift1;
			}
			set
			{
				if ((this._Gift1 != value))
				{
					this.OnGift1Changing(value);
					this.SendPropertyChanging();
					this._Gift1 = value;
					this.SendPropertyChanged("Gift1");
					this.OnGift1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DropShipID", DbType="Int")]
		public System.Nullable<int> DropShipID
		{
			get
			{
				return this._DropShipID;
			}
			set
			{
				if ((this._DropShipID != value))
				{
					this.OnDropShipIDChanging(value);
					this.SendPropertyChanging();
					this._DropShipID = value;
					this.SendPropertyChanged("DropShipID");
					this.OnDropShipIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cust_to_org")]
	public partial class Cust_to_org : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OrgID;
		
		private string _FirstName;
		
		private string _Lastname;
		
		private string _email;
		
		private int _CUSTID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrgIDChanging(string value);
    partial void OnOrgIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastnameChanging(string value);
    partial void OnLastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnCUSTIDChanging(int value);
    partial void OnCUSTIDChanged();
    #endregion
		
		public Cust_to_org()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgID", DbType="NChar(10)")]
		public string OrgID
		{
			get
			{
				return this._OrgID;
			}
			set
			{
				if ((this._OrgID != value))
				{
					this.OnOrgIDChanging(value);
					this.SendPropertyChanging();
					this._OrgID = value;
					this.SendPropertyChanged("OrgID");
					this.OnOrgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NChar(100)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this.OnLastnameChanging(value);
					this.SendPropertyChanging();
					this._Lastname = value;
					this.SendPropertyChanged("Lastname");
					this.OnLastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CUSTID
		{
			get
			{
				return this._CUSTID;
			}
			set
			{
				if ((this._CUSTID != value))
				{
					this.OnCUSTIDChanging(value);
					this.SendPropertyChanging();
					this._CUSTID = value;
					this.SendPropertyChanged("CUSTID");
					this.OnCUSTIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderDetails")]
	public partial class OrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LineNumber;
		
		private string _OrderNumber;
		
		private string _ProductCode;
		
		private string _ProductName;
		
		private string _Price;
		
		private string _Warehouse;
		
		private string _ShipStatus;
		
		private System.Nullable<bool> _GiftPaid;
		
		private string _OrgId;
		
		private System.Nullable<int> _qty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLineNumberChanging(int value);
    partial void OnLineNumberChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnProductCodeChanging(string value);
    partial void OnProductCodeChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnWarehouseChanging(string value);
    partial void OnWarehouseChanged();
    partial void OnShipStatusChanging(string value);
    partial void OnShipStatusChanged();
    partial void OnGiftPaidChanging(System.Nullable<bool> value);
    partial void OnGiftPaidChanged();
    partial void OnOrgIdChanging(string value);
    partial void OnOrgIdChanged();
    partial void OnqtyChanging(System.Nullable<int> value);
    partial void OnqtyChanged();
    #endregion
		
		public OrderDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNumber", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LineNumber
		{
			get
			{
				return this._LineNumber;
			}
			set
			{
				if ((this._LineNumber != value))
				{
					this.OnLineNumberChanging(value);
					this.SendPropertyChanging();
					this._LineNumber = value;
					this.SendPropertyChanged("LineNumber");
					this.OnLineNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="NVarChar(50)")]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warehouse", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Warehouse
		{
			get
			{
				return this._Warehouse;
			}
			set
			{
				if ((this._Warehouse != value))
				{
					this.OnWarehouseChanging(value);
					this.SendPropertyChanging();
					this._Warehouse = value;
					this.SendPropertyChanged("Warehouse");
					this.OnWarehouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipStatus", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipStatus
		{
			get
			{
				return this._ShipStatus;
			}
			set
			{
				if ((this._ShipStatus != value))
				{
					this.OnShipStatusChanging(value);
					this.SendPropertyChanging();
					this._ShipStatus = value;
					this.SendPropertyChanged("ShipStatus");
					this.OnShipStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiftPaid", DbType="Bit")]
		public System.Nullable<bool> GiftPaid
		{
			get
			{
				return this._GiftPaid;
			}
			set
			{
				if ((this._GiftPaid != value))
				{
					this.OnGiftPaidChanging(value);
					this.SendPropertyChanging();
					this._GiftPaid = value;
					this.SendPropertyChanged("GiftPaid");
					this.OnGiftPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="NChar(10)")]
		public string OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					this.OnOrgIdChanging(value);
					this.SendPropertyChanging();
					this._OrgId = value;
					this.SendPropertyChanged("OrgId");
					this.OnOrgIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
		public System.Nullable<int> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xml")]
	public partial class xml : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _xml1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onxml1Changing(string value);
    partial void Onxml1Changed();
    #endregion
		
		public xml()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="xml", Storage="_xml1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string xml1
		{
			get
			{
				return this._xml1;
			}
			set
			{
				if ((this._xml1 != value))
				{
					this.Onxml1Changing(value);
					this.SendPropertyChanging();
					this._xml1 = value;
					this.SendPropertyChanged("xml1");
					this.Onxml1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderHeader")]
	public partial class OrderHeader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OrderNumber;
		
		private string _BillingAddr1;
		
		private string _BillingAddr2;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private string _CompanyName;
		
		private string _BillingFirstName;
		
		private string _BillingLastName;
		
		private string _PhoneNumber;
		
		private string _CustomerIPAddr;
		
		private string _CustomerID;
		
		private string _Gift;
		
		private string _OrderComments;
		
		private string _OrderDate;
		
		private string _OrderStatus;
		
		private string _ShipToAddr1;
		
		private string _ShipToAddr2;
		
		private string _ShipCompanyName;
		
		private string _ShipCity;
		
		private string _ShipState;
		
		private string _ShipZipCode;
		
		private string _ShipPhone;
		
		private string _OrgID;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _OrderDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnBillingAddr1Changing(string value);
    partial void OnBillingAddr1Changed();
    partial void OnBillingAddr2Changing(string value);
    partial void OnBillingAddr2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnBillingFirstNameChanging(string value);
    partial void OnBillingFirstNameChanged();
    partial void OnBillingLastNameChanging(string value);
    partial void OnBillingLastNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCustomerIPAddrChanging(string value);
    partial void OnCustomerIPAddrChanged();
    partial void OnCustomerIDChanging(string value);
    partial void OnCustomerIDChanged();
    partial void OnGiftChanging(string value);
    partial void OnGiftChanged();
    partial void OnOrderCommentsChanging(string value);
    partial void OnOrderCommentsChanged();
    partial void OnOrderDateChanging(string value);
    partial void OnOrderDateChanged();
    partial void OnOrderStatusChanging(string value);
    partial void OnOrderStatusChanged();
    partial void OnShipToAddr1Changing(string value);
    partial void OnShipToAddr1Changed();
    partial void OnShipToAddr2Changing(string value);
    partial void OnShipToAddr2Changed();
    partial void OnShipCompanyNameChanging(string value);
    partial void OnShipCompanyNameChanged();
    partial void OnShipCityChanging(string value);
    partial void OnShipCityChanged();
    partial void OnShipStateChanging(string value);
    partial void OnShipStateChanged();
    partial void OnShipZipCodeChanging(string value);
    partial void OnShipZipCodeChanged();
    partial void OnShipPhoneChanging(string value);
    partial void OnShipPhoneChanged();
    partial void OnOrgIDChanging(string value);
    partial void OnOrgIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnOrderDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateTimeChanged();
    #endregion
		
		public OrderHeader()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddr1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BillingAddr1
		{
			get
			{
				return this._BillingAddr1;
			}
			set
			{
				if ((this._BillingAddr1 != value))
				{
					this.OnBillingAddr1Changing(value);
					this.SendPropertyChanging();
					this._BillingAddr1 = value;
					this.SendPropertyChanged("BillingAddr1");
					this.OnBillingAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddr2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BillingAddr2
		{
			get
			{
				return this._BillingAddr2;
			}
			set
			{
				if ((this._BillingAddr2 != value))
				{
					this.OnBillingAddr2Changing(value);
					this.SendPropertyChanging();
					this._BillingAddr2 = value;
					this.SendPropertyChanged("BillingAddr2");
					this.OnBillingAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingFirstName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BillingFirstName
		{
			get
			{
				return this._BillingFirstName;
			}
			set
			{
				if ((this._BillingFirstName != value))
				{
					this.OnBillingFirstNameChanging(value);
					this.SendPropertyChanging();
					this._BillingFirstName = value;
					this.SendPropertyChanged("BillingFirstName");
					this.OnBillingFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingLastName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BillingLastName
		{
			get
			{
				return this._BillingLastName;
			}
			set
			{
				if ((this._BillingLastName != value))
				{
					this.OnBillingLastNameChanging(value);
					this.SendPropertyChanging();
					this._BillingLastName = value;
					this.SendPropertyChanged("BillingLastName");
					this.OnBillingLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerIPAddr", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CustomerIPAddr
		{
			get
			{
				return this._CustomerIPAddr;
			}
			set
			{
				if ((this._CustomerIPAddr != value))
				{
					this.OnCustomerIPAddrChanging(value);
					this.SendPropertyChanging();
					this._CustomerIPAddr = value;
					this.SendPropertyChanged("CustomerIPAddr");
					this.OnCustomerIPAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gift", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Gift
		{
			get
			{
				return this._Gift;
			}
			set
			{
				if ((this._Gift != value))
				{
					this.OnGiftChanging(value);
					this.SendPropertyChanging();
					this._Gift = value;
					this.SendPropertyChanged("Gift");
					this.OnGiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderComments", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OrderComments
		{
			get
			{
				return this._OrderComments;
			}
			set
			{
				if ((this._OrderComments != value))
				{
					this.OnOrderCommentsChanging(value);
					this.SendPropertyChanging();
					this._OrderComments = value;
					this.SendPropertyChanged("OrderComments");
					this.OnOrderCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				if ((this._OrderDate != value))
				{
					this.OnOrderDateChanging(value);
					this.SendPropertyChanging();
					this._OrderDate = value;
					this.SendPropertyChanged("OrderDate");
					this.OnOrderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatus", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OrderStatus
		{
			get
			{
				return this._OrderStatus;
			}
			set
			{
				if ((this._OrderStatus != value))
				{
					this.OnOrderStatusChanging(value);
					this.SendPropertyChanging();
					this._OrderStatus = value;
					this.SendPropertyChanged("OrderStatus");
					this.OnOrderStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAddr1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipToAddr1
		{
			get
			{
				return this._ShipToAddr1;
			}
			set
			{
				if ((this._ShipToAddr1 != value))
				{
					this.OnShipToAddr1Changing(value);
					this.SendPropertyChanging();
					this._ShipToAddr1 = value;
					this.SendPropertyChanged("ShipToAddr1");
					this.OnShipToAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAddr2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipToAddr2
		{
			get
			{
				return this._ShipToAddr2;
			}
			set
			{
				if ((this._ShipToAddr2 != value))
				{
					this.OnShipToAddr2Changing(value);
					this.SendPropertyChanging();
					this._ShipToAddr2 = value;
					this.SendPropertyChanged("ShipToAddr2");
					this.OnShipToAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCompanyName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipCompanyName
		{
			get
			{
				return this._ShipCompanyName;
			}
			set
			{
				if ((this._ShipCompanyName != value))
				{
					this.OnShipCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._ShipCompanyName = value;
					this.SendPropertyChanged("ShipCompanyName");
					this.OnShipCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCity", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipCity
		{
			get
			{
				return this._ShipCity;
			}
			set
			{
				if ((this._ShipCity != value))
				{
					this.OnShipCityChanging(value);
					this.SendPropertyChanging();
					this._ShipCity = value;
					this.SendPropertyChanged("ShipCity");
					this.OnShipCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipState", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipState
		{
			get
			{
				return this._ShipState;
			}
			set
			{
				if ((this._ShipState != value))
				{
					this.OnShipStateChanging(value);
					this.SendPropertyChanging();
					this._ShipState = value;
					this.SendPropertyChanged("ShipState");
					this.OnShipStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipZipCode", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ShipZipCode
		{
			get
			{
				return this._ShipZipCode;
			}
			set
			{
				if ((this._ShipZipCode != value))
				{
					this.OnShipZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ShipZipCode = value;
					this.SendPropertyChanged("ShipZipCode");
					this.OnShipZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPhone", DbType="NChar(10)")]
		public string ShipPhone
		{
			get
			{
				return this._ShipPhone;
			}
			set
			{
				if ((this._ShipPhone != value))
				{
					this.OnShipPhoneChanging(value);
					this.SendPropertyChanging();
					this._ShipPhone = value;
					this.SendPropertyChanged("ShipPhone");
					this.OnShipPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgID", DbType="NChar(10)")]
		public string OrgID
		{
			get
			{
				return this._OrgID;
			}
			set
			{
				if ((this._OrgID != value))
				{
					this.OnOrgIDChanging(value);
					this.SendPropertyChanging();
					this._OrgID = value;
					this.SendPropertyChanged("OrgID");
					this.OnOrgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderDateTime
		{
			get
			{
				return this._OrderDateTime;
			}
			set
			{
				if ((this._OrderDateTime != value))
				{
					this.OnOrderDateTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderDateTime = value;
					this.SendPropertyChanged("OrderDateTime");
					this.OnOrderDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetOrgIDResult
	{
		
		private string _ORGID;
		
		public GetOrgIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORGID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ORGID
		{
			get
			{
				return this._ORGID;
			}
			set
			{
				if ((this._ORGID != value))
				{
					this._ORGID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
