#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestServiceWithKey1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="poopstats")]
	public partial class PoopStatsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PoopStatsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["poopstatsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PoopStatsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopStatsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopStatsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoopStatsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateorInsertOrderDetails")]
		public int UpdateorInsertOrderDetails(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDetailID", DbType="Int")] System.Nullable<int> orderDetailID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AutoDropShip", DbType="NChar(1)")] System.Nullable<char> autoDropShip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FreeShippingItem", DbType="NChar(1)")] System.Nullable<char> freeShippingItem, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiftTrakNumber", DbType="Int")] System.Nullable<int> giftTrakNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiftWrap", DbType="NChar(1)")] System.Nullable<char> giftWrap, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiftWrapCost", DbType="Money")] System.Nullable<decimal> giftWrapCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiftWrapNote", DbType="NChar(200)")] string giftWrapNote, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsKitID", DbType="NChar(1)")] System.Nullable<char> isKitID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KitID", DbType="Int")] System.Nullable<int> kitID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Locked", DbType="NChar(1)")] System.Nullable<char> locked, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnOrder_Qty", DbType="Int")] System.Nullable<int> onOrder_Qty, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionIDs", DbType="Int")] System.Nullable<int> optionIDs, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Options", DbType="NChar(100)")] string options, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCode", DbType="NChar(100)")] string productCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="NChar(200)")] string productName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrice", DbType="Money")] System.Nullable<decimal> productPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductWeight", DbType="Int")] System.Nullable<int> productWeight, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtyOnBackOrder", DbType="Int")] System.Nullable<int> qtyOnBackOrder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtyOnHold", DbType="Int")] System.Nullable<int> qtyOnHold, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtyShipped", DbType="Int")] System.Nullable<int> qtyShipped, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalPrice", DbType="Money")] System.Nullable<decimal> totalPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Warehouses", DbType="NChar(20)")] string warehouses)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderDetailID, autoDropShip, freeShippingItem, giftTrakNumber, giftWrap, giftWrapCost, giftWrapNote, isKitID, kitID, locked, onOrder_Qty, optionIDs, options, orderID, productCode, productID, productName, productPrice, productWeight, qtyOnBackOrder, qtyOnHold, qtyShipped, quantity, totalPrice, warehouses);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetGiftTotal")]
		public ISingleResult<GetGiftTotalResult> GetGiftTotal([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORGID", DbType="NChar(10)")] string oRGID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oRGID);
			return ((ISingleResult<GetGiftTotalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOrgName")]
		public ISingleResult<GetOrgNameResult> GetOrgName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORGID", DbType="NChar(10)")] string oRGID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oRGID);
			return ((ISingleResult<GetOrgNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateorInsertOrders")]
		public int UpdateorInsertOrders(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderNumber", DbType="Int")] System.Nullable<int> orderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNumber", DbType="NChar(100)")] string accountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountType", DbType="NChar(10)")] string accountType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressValidated", DbType="NChar(1)")] System.Nullable<char> addressValidated, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Affiliate_Commissionable_Value", DbType="Money")] System.Nullable<decimal> affiliate_Commissionable_Value, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AuthHash", DbType="NChar(100)")] string authHash, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankName", DbType="NChar(200)")] string bankName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingAddress1", DbType="NChar(300)")] string billingAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingAddress2", DbType="NChar(300)")] string billingAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingCity", DbType="NChar(100)")] string billingCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingCompanyName", DbType="NChar(100)")] string billingCompanyName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingCountry", DbType="NChar(20)")] string billingCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingFaxNumber", DbType="NChar(10)")] string billingFaxNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingFirstName", DbType="NChar(30)")] string billingFirstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingLastName", DbType="NChar(30)")] string billingLastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingPhoneNumber", DbType="NChar(10)")] string billingPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingPostalCode", DbType="NChar(10)")] string billingPostalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingState", DbType="NChar(2)")] string billingState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardHoldersName", DbType="NChar(60)")] string cardHoldersName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CC_Last4", DbType="Int")] System.Nullable<int> cC_Last4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckNumber", DbType="Int")] System.Nullable<int> checkNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardExpDate", DbType="DateTime")] System.Nullable<System.DateTime> creditCardExpDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardIssueDate", DbType="DateTime")] System.Nullable<System.DateTime> creditCardIssueDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreditCardIssueNumber", DbType="NChar(200)")] string creditCardIssueNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_IPAddress", DbType="NChar(15)")] string customer_IPAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAGift", DbType="NChar(1)")] System.Nullable<char> isAGift, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Locked", DbType="NChar(1)")] System.Nullable<char> locked, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MICR", DbType="NChar(10)")] string mICR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Order_Comments", DbType="NChar(300)")] string order_Comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Order_Entry_System", DbType="NChar(100)")] string order_Entry_System, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDate", DbType="DateTime")] System.Nullable<System.DateTime> orderDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderStatus", DbType="NChar(200)")] string orderStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentAmount", DbType="Money")] System.Nullable<decimal> paymentAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentMethodID", DbType="Int")] System.Nullable<int> paymentMethodID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PONum", DbType="NChar(20)")] string pONum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoutingNumber", DbType="NChar(20)")] string routingNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTax1", DbType="Money")] System.Nullable<decimal> salesTax1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTax2", DbType="Money")] System.Nullable<decimal> salesTax2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTax3", DbType="Money")] System.Nullable<decimal> salesTax3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTaxRate", DbType="Int")] System.Nullable<int> salesTaxRate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTaxRate1", DbType="Int")] System.Nullable<int> salesTaxRate1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTaxRate2", DbType="Int")] System.Nullable<int> salesTaxRate2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesTaxRate3", DbType="Int")] System.Nullable<int> salesTaxRate3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipAddress1", DbType="NChar(300)")] string shipAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipAddress2", DbType="NChar(300)")] string shipAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipCity", DbType="NChar(100)")] string shipCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipCompanyName", DbType="NChar(100)")] string shipCompanyName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipCountry", DbType="NChar(100)")] string shipCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipFaxNumber", DbType="NChar(15)")] string shipFaxNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipFirstName", DbType="NChar(30)")] string shipFirstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipLastName", DbType="NChar(30)")] string shipLastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipPhoneNumber", DbType="NChar(15)")] string shipPhoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Shipping_Locked", DbType="NChar(1)")] System.Nullable<char> shipping_Locked, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingMethodID", DbType="Int")] System.Nullable<int> shippingMethodID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipResidential", DbType="NChar(1)")] System.Nullable<char> shipResidential, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipState", DbType="NChar(2)")] string shipState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipPostalCode", DbType="NChar(10)")] string shipPostalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stock_Priority", DbType="Int")] System.Nullable<int> stock_Priority, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tax1_Title", DbType="NChar(20)")] string tax1_Title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tax2_Title", DbType="NChar(20)")] string tax2_Title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tax3_Title", DbType="NChar(20)")] string tax3_Title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_Payment_Authorized", DbType="Money")] System.Nullable<decimal> total_Payment_Authorized, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_Payment_Received", DbType="Money")] System.Nullable<decimal> total_Payment_Received, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalShippingCost", DbType="Money")] System.Nullable<decimal> totalShippingCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VendorID", DbType="Int")] System.Nullable<int> vendorID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sent", DbType="Bit")] System.Nullable<bool> sent, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrgId", DbType="NChar(10)")] string orgId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderNumber, accountNumber, accountType, addressValidated, affiliate_Commissionable_Value, authHash, bankName, billingAddress1, billingAddress2, billingCity, billingCompanyName, billingCountry, billingFaxNumber, billingFirstName, billingLastName, billingPhoneNumber, billingPostalCode, billingState, cardHoldersName, cC_Last4, checkNumber, creditCardExpDate, creditCardIssueDate, creditCardIssueNumber, customer_IPAddress, customerID, isAGift, locked, mICR, order_Comments, order_Entry_System, orderDate, orderStatus, paymentAmount, paymentMethodID, pONum, routingNumber, salesTax1, salesTax2, salesTax3, salesTaxRate, salesTaxRate1, salesTaxRate2, salesTaxRate3, shipAddress1, shipAddress2, shipCity, shipCompanyName, shipCountry, shipFaxNumber, shipFirstName, shipLastName, shipPhoneNumber, shipping_Locked, shippingMethodID, shipResidential, shipState, shipPostalCode, stock_Priority, tax1_Title, tax2_Title, tax3_Title, total_Payment_Authorized, total_Payment_Received, totalShippingCost, vendorID, sent, orgId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetXmlOrders")]
		public ISingleResult<GetXmlOrdersResult> GetXmlOrders([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orgid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orgid);
			return ((ISingleResult<GetXmlOrdersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDropId")]
		public ISingleResult<GetDropIdResult> GetDropId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Guid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> guid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guid);
			return ((ISingleResult<GetDropIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddError")]
		public int AddError([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(400)")] string error)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), error);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetGiftTotalResult
	{
		
		private System.Nullable<decimal> _Total;
		
		public GetGiftTotalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class GetOrgNameResult
	{
		
		private string _ORG_name;
		
		public GetOrgNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_name", DbType="NChar(200)")]
		public string ORG_name
		{
			get
			{
				return this._ORG_name;
			}
			set
			{
				if ((this._ORG_name != value))
				{
					this._ORG_name = value;
				}
			}
		}
	}
	
	public partial class GetXmlOrdersResult
	{
		
		private string _XML_F52E2B61_18A1_11d1_B105_00805F49916B;
		
		public GetXmlOrdersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[XML_F52E2B61-18A1-11d1-B105-00805F49916B]", Storage="_XML_F52E2B61_18A1_11d1_B105_00805F49916B", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string XML_F52E2B61_18A1_11d1_B105_00805F49916B
		{
			get
			{
				return this._XML_F52E2B61_18A1_11d1_B105_00805F49916B;
			}
			set
			{
				if ((this._XML_F52E2B61_18A1_11d1_B105_00805F49916B != value))
				{
					this._XML_F52E2B61_18A1_11d1_B105_00805F49916B = value;
				}
			}
		}
	}
	
	public partial class GetDropIdResult
	{
		
		private int _Dropshipid;
		
		public GetDropIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dropshipid", DbType="Int NOT NULL")]
		public int Dropshipid
		{
			get
			{
				return this._Dropshipid;
			}
			set
			{
				if ((this._Dropshipid != value))
				{
					this._Dropshipid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
